**Reading data from csv file into NumPy array**

**Mathematical operations with NumPy arrays**

Some of the content for this tutorial was adapted from https://www.dataquest.io/blog/numpy-tutorial-python/

In [14]:
import numpy as np

In [15]:
data_file_name = "diabetes_num.csv"

ds = np.genfromtxt(data_file_name, delimiter=",", skip_header=1)

In [16]:
ds[0:3, 3]

array([ 23.,  33.,  42.])

** 1-Dimensional Array Math **

If you do any of the basic mathematical operations (/, *, -, +, ^) with an array and a value, it will apply the operation to each of the elements in the array.

In [23]:
# For example, we could add 1 to the age column of our dataset

print(ds[:10, 6]) # print first 10 rows of column 6 of the diabetes dataset before adding 1

ds_plus = ds[:,6] + 1

# Note that the above operation won't change the ds array - it will return 
# a new 1-dimensional array where 1 has been added to each element in the age column.

print(ds_plus[:10]) # print first 10 rows of column 6 of the diabetes dataset after adding 1


[ 51.  56.  36.  63.  35.  43.  60.  49.  74.  31.]
[ 52.  57.  37.  64.  36.  44.  61.  50.  75.  32.]


In [25]:
# If we wanted modify the array in place instead, we can use += operator:

ds[:,6] += 1
ds[:10,6] # print first 10 rows of column 6 of the diabetes dataset after adding 1

array([ 53.,  58.,  38.,  65.,  37.,  45.,  62.,  51.,  76.,  33.])

In [27]:
# All the other operations work the same way. 
# For example, if we want to multiply each of the cholesterol value by 2, we would do the following:
ds_mult = ds[:, 1] * 2
print(ds_mult[:10])

# If we wanted to modify the original array in place, we would use the following logic:
ds[:,1] *= 2
print(ds[:10, 1])

[ 1772.  1616.  1388.  1368.  1348.  1288.  1272.  1228.  1224.  1220.]
[ 1772.  1616.  1388.  1368.  1348.  1288.  1272.  1228.  1224.  1220.]
