In [2]:
import numpy as np
import matplotlib.pyplot as pp

In [3]:
python_list = [1,2,3,4,5]
a = np.array(python_list)

a

a.dtype

dtype('int64')

In [4]:
a = np.array(python_list, dtype=np.float64)
a

array([ 1.,  2.,  3.,  4.,  5.])

In [5]:
# Number of dimensions
a.ndim

1

In [6]:
# Array shape
a.shape

(5,)

In [7]:
# Array size
a.size

5

In [8]:
a_zeros = np.zeros((3,3), dtype=np.int32)
a_zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [9]:
a_empty = np.empty((4,4), dtype=np.int32)
a_empty

array([[         0,  805306368, 1153981375,       2045],
       [         4,          0,          0,          0],
       [         0,          0,          0,          0],
       [         0,  805306368, 1154004554,     264189]], dtype=int32)

In [10]:
# Evenly spaced array
np.linspace(0, 10, 5)

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [11]:
# Array with a range and a step
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [12]:
# Random values-filled array
np.random.standard_normal((2,4))

array([[-0.26335779,  0.2879354 ,  0.75135616,  0.65675224],
       [ 0.58838321,  2.49188382, -1.19668379, -0.07591917]])

In [13]:
# Vertical stacking
a = np.random.standard_normal((2,3))
b = np.random.standard_normal((2,3))
np.vstack([a,b])

array([[ 0.75990163, -0.43616863, -0.56806608],
       [ 0.93610372,  0.63982358, -0.00311777],
       [-1.29963554,  1.73378541,  1.08699984],
       [-0.2993648 ,  0.80676435, -2.24800183]])

In [15]:
# Horizontal stacking
a = np.random.standard_normal((2,3))
print(a)
b = np.random.standard_normal((2,3))
print(b)
np.hstack([a,b])

[[-0.43683989  1.84077687  1.19109334]
 [ 1.35016031  0.93144678 -0.68869588]]
[[-1.28202008 -0.16481482 -0.17143903]
 [ 0.46855168 -0.10672595 -0.44886844]]


array([[-0.43683989,  1.84077687,  1.19109334, -1.28202008, -0.16481482,
        -0.17143903],
       [ 1.35016031,  0.93144678, -0.68869588,  0.46855168, -0.10672595,
        -0.44886844]])

In [26]:
# Transposing an array
a.transpose()

array([[ 0.50771501, -0.29498806],
       [ 0.48518878,  0.72108004],
       [-0.2845574 , -0.92501124]])

In [27]:
# Saving an array
np.save("ExampleSavedArray.npy", a)

In [29]:
a2 = np.load("ExampleSavedArray.npy")
a2

array([[ 0.50771501,  0.48518878, -0.2845574 ],
       [-0.29498806,  0.72108004, -0.92501124]])